services:
  # autoware:
  #   image: ghcr.io/autowarefoundation/autoware:universe
  #   volumes:
  #     - $HOME/autoware_map:/root/autoware_map
  #   command: >
  #     ros2 launch autoware_launch
  #     planning_simulator.launch.xml
  #     map_path:='$(ros2 pkg prefix --share kashiwanoha_map)/map'
  #     vehicle_model:=sample_vehicle
  #     sensor_model:=sample_sensor_kit
  #     scenario_simulation:=true
  #     rviz:=false

  # visualizer:
  #   image: ghcr.io/oguzkaganozt/autoware-oz:visualizer-amd64
  #   ports:
  #     - 6080:6080

  scenario_simulator:
    image: ghcr.io/oguzkaganozt/autoware-oz:scenario-simulator-amd64
    volumes:
      - $HOME/autoware_map:/root/autoware_map
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    command: >
      ros2 launch scenario_test_runner scenario_test_runner.launch.py
      record:=false
      scenario:='$(find-pkg-share scenario_test_runner)/scenario/sample.yaml'
      sensor_model:=sample_sensor_kit
      vehicle_model:=sample_vehicle
      initialize_duration:=90
      global_timeout:=120
      global_frame_rate:=20

